symfony/src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
#[ORM\Table(name: '`products`')]
class Product
{

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $name;

    #[ORM\Column(type: 'integer')]
    private $price;

    #[ORM\Column(type: 'string', length: 255)]
    private $description;

    #[ORM\ManyToOne(targetEntity: Category::class, cascade: ['persist', 'remove'], inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: false)]
    private $category;

    #[ORM\Column(type: 'datetime')]
    #[Gedmo\Timestampable(on: 'create')]
    private $createdAt;

    #[ORM\Column(type: 'integer')]
    private $warehouse;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: ProductField::class, cascade: ['persist', 'remove'], orphanRemoval: true)]
    private $productFields;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: ImageProduct::class, cascade: ['persist', 'remove'])]
    private $imageProducts;

    #[ORM\Column(length: 16)]
    private $code;

    #[ORM\Column(length: 128, unique: true, nullable: true)]
    #[Gedmo\Slug(fields: ['name', 'code'])]
    private $slug;

    #[ORM\Column(type: 'integer', unique: true)]
    private $idApi;

    public function __construct()
    {
        $this->productFields = new ArrayCollection();
        $this->imageProducts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getWarehouse(): ?int
    {
        return $this->warehouse;
    }

    public function setWarehouse(int $warehouse): self
    {
        $this->warehouse = $warehouse;

        return $this;
    }

    public function getProductFields(): Collection
    {
        return $this->productFields;
    }

    public function addProductField(ProductField $productField): self
    {
        if (!$this->productFields->contains($productField)) {
            $this->productFields[] = $productField;
            $productField->setProduct($this);
        }

        return $this;
    }

    public function removeProductField(ProductField $productField): self
    {
        $this->productFields->removeElement($productField);
        return $this;
    }

    public function getProductPromo(): ?string
    {
        return $this->imageProducts->first() ? $this->imageProducts->first()->getImage()->getFilename() : null;
    }

    /**
     * @return Collection<int, ImageProduct>
     */
    public function getImageProducts(): Collection
    {
        return $this->imageProducts;
    }

    public function addImageProduct(ImageProduct $imageProduct): self
    {
        if (!$this->imageProducts->contains($imageProduct)) {
            $this->imageProducts[] = $imageProduct;
            $imageProduct->setProduct($this);
        }

        return $this;
    }

    public function removeImageProduct(ImageProduct $imageProduct): self
    {
        if ($this->imageProducts->removeElement($imageProduct)) {
            // set the owning side to null (unless already changed)
            if ($imageProduct->getProduct() === $this) {
                $imageProduct->setProduct(null);
            }
        }

        return $this;
    }

    public function getSlug(): mixed
    {
        return $this->slug;
    }

    public function getCode(): mixed
    {
        return $this->code;
    }

    public function setCode($code): self
    {
        $this->code = $code;

        return $this;
    }

    public function getIdApi(): ?int
    {
        return $this->idApi;
    }

    public function setIdApi($idApi): self
    {
        $this->idApi = $idApi;

        return $this;
    }
}

symfony/src/Form/ProductType.php
<?php

namespace App\Form;

use App\Entity\Category;
use App\Entity\Product;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('price')
            ->add('description')
            ->add('category', EntityType::class, [
                'class' => Category::class,
                'choice_label' => 'name',
            ])
            ->add('warehouse')
            ->add('productFields', CollectionType::class, [
                'label' => false,
                'entry_type' => ProductFieldType::class,
                'by_reference' => false,
                'prototype' => true,
                'allow_add' => true,
                'allow_delete' => true,
            ])
            ->add('imageProducts', CollectionType::class, [
                'label' => false,
                'entry_type' => ImageProductType::class,
                'allow_add' => true,
                'by_reference' => false,
                'allow_delete' => true,
                'prototype' => true,
            ]);

    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
        ]);
    }
}

symfony/src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Form\AddToCartType;
use App\Form\ProductType;
use App\Manager\CartManager;
use App\Service\RedisService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class ProductController extends AbstractController
{
    public function __construct(
        private readonly RedisService $redisService
    )
    {}

    public function showProduct(Product $product, Request $request, CartManager $cartManager): Response
    {
        $productDTO = $this->redisService->getProductFromRedis($product->getSlug());

        $form = $this->createForm(AddToCartType::class);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $item = $form->getData();
            $item->setProduct($product);

            $cart = $cartManager->getCurrentCart();
            $cart
                ->addItem($item)
                ->setUpdatedAt(new \DateTime());

            $cartManager->save($cart);

            return $this->redirectToRoute('view_product', ['product' => $product->getId(),  'productDTO' => $productDTO]);
        }

        return $this->render('product/product.html.twig', [
            'product' => $product,
            'productDTO' => $productDTO,
            'form' => $form->createView()
        ]);
    }

    public function addProduct(Request $request, EntityManagerInterface $em): Response
    {
        $product = new Product();
        $form = $this->createForm(ProductType::class, $product);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $em->persist($product);
            $em->flush();

            return $this->redirectToRoute('index');
        }

        return $this->render('product/product_manipulation.html.twig', [
            'form' => $form->createView(),
            'add' => 'method'
        ]);
    }

    public function editProduct(Product $product, Request $request, EntityManagerInterface $em): Response
    {
        $form = $this->createForm(ProductType::class, $product);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $em->persist($product);
            $em->flush();

            return $this->redirectToRoute('index');
        }

        return $this->render('product/product_manipulation.html.twig', [
            'form' => $form->createView(),
            'edit' => 'method'
        ]);
    }

    public function deleteProduct(EntityManagerInterface $em, Product $product): Response
    {
        $em->remove($product);
        $em->flush();

        return $this->redirectToRoute('index');
    }
}

symfony/templates/product/product.html.twig
{% extends 'base.html.twig' %}

{% block title %}Интернет-магазин{% endblock %}

{% block body %}
    <div class="container content">
        <div class="row">
            <div class="col-md-4">
                {{ render(controller('App\\Controller\\IndexController::showCategories')) }}
            </div>
            <div class="col-md-8">
                <div class="col-md-8 products">
                    <div class="row">
                        <div class="col-sm-6">
                            {{ include('product/product_block.html.twig') }}
                            {{ form_start(form, {'attr': {'class': 'mt-4 p-4 bg-light'}}) }}
                            <div class="form-group">
                                {{ form_label(form.quantity, 'Количество') }}
                                {{ form_widget(form.quantity, {
                                    'attr': {
                                        'class': 'form-control ' ~ (form.quantity.vars.valid ? '' : 'is-invalid')
                                    }
                                }) }}
                                <div class="invalid-feedback">
                                    {{ form_errors(form.quantity) }}
                                </div>
                            </div>
                            <br>
                            {{ form_widget(form.add, {'attr': {'class': 'btn btn-warning w-100'}}) }}
                            {{ form_end(form) }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

symfony/templates/product/product_block.html.twig
<div class="product">
        {% if isProductInCart(product) %}
            <button class="btn btn-outline-success btn-sm subscribe add-to-cart active" data-id="{{ product.id }}">В корзину</button>
        {% else %}
            <button class="btn btn-outline-success btn-sm subscribe add-to-cart" data-id="{{ product.id }}">В корзину</button>
        {% endif %}

    <div class="product-img">
        <img src="{{ ('/uploads/' ~ product.productPromo)|imagine_filter('my_thumb') }}" alt="home-1"
             class="img-responsive">
        {% if productDTO is defined %}
        <img src="{{ productDTO.image }}" alt="home-1" class="img-responsive">
        {% endif %}
    </div>
    {% if app.user %}
        {% if 'ROLE_ADMIN' in app.user.roles %}
            <div class="product-tools">
                <p class="product-title-tools-edit">
                    <a href="{{ path('edit_product', {product: product.id}) }}"
                       class="btn btn-outline-success btn-sm  list-group-item">редактировать</a>
                </p>
                <p class="product-title-tools-delete">
                    <a href="{{ path('delete_product', {product: product.id}) }}" class="btn btn-outline-success btn-sm  list-group-item">удалить</a>
                </p>
            </div>
        {% endif %}
    {% endif %}
    <p class="product-title">
        <a href="{{ path('view_product', {slug: product.slug}) }}">{{ product.name }}</a>
    </p>
    <p class="product-desc">{{ product.description }}</p>
    <p class="product-price">Цена: {{ product.price | price }}</p>
</div>

symfony/templates/product/product_manipulation.html.twig
{% extends 'base.html.twig' %}
{% block title %}
    {% if edit is defined %}
        Редактировать товар
    {% else %}
        Добавить товар
    {% endif %}
{% endblock %}
{% block body %}
    <div class="container content">
        <div class="row">
            <div class="col-md-4">
                {{ render(controller('App\\Controller\\IndexController::showCategories')) }}
            </div>
            <div class="col-md-8">

                {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
                {{ form_label(form.name, 'Название', {'label_attr': {'class': 'col-md-1 control-label'}}) }}
                {{ form_widget(form.name) }}
                {{ form_label(form.description, 'Описание', {'label_attr': {'class': 'col-md-1 control-label'}}) }}
                {{ form_widget(form.description) }}
                {{ form_label(form.price, 'Цена', {'label_attr': {'class': 'col-md-1 control-label'}}) }}
                {{ form_widget(form.price) }}
                {{ form_label(form.warehouse, 'Колличество на складе', {'label_attr': {'class': 'col-md-4 control-label'}}) }}
                {{ form_widget(form.warehouse) }}
                <ul id="fields-list"
                    data-prototype="{{ form_widget(form.productFields.vars.prototype)|e }}"
                    data-widget-tags="{{ '<li></li>'|e }}">

                    {% for productField in form.productFields %}
                        <li>
                            {{ form_row(productField.name) }}
                            {{ form_row(productField.value) }}

                            <a href="" class="remove-another-collection-widget" data-list="#delete_fields-list">
                                Удалить свойство товара
                            </a>
                        </li>

                    {% endfor %}
                </ul>
                <a href="" class="add-another-collection-widget" data-list="#fields-list">Добавить свойство товара</a>
                <br> <br>
                <label>
                    <a class="btn btn-secondary">Добавить картинку</a>
                    <input class="file-upload" type="file" style="display: none">
                </label>
                <div id="image-container" class="collection-container"
                    data-prototype="{{ form_widget(form.imageProducts.vars.prototype)|e }}"
                    data-widget-tags="{{ '<div class="image-item"></div>'|e }}">
                    {% for image in form.imageProducts %}
                        <div class="image-item">
                            <div class="img-relative">
                                <a href="#" class="icon-deleted">X</a>
                                <img src="/uploads/{{ image.vars.value.image.filename }}" class="img-add">
                            </div>
                            {{ form_widget(image) }}
                        </div>
                    {% endfor %}
                </div>

                {{ form_label(form.category, 'Категория', {'label_attr': {'class': 'col-md-2 control-label'}}) }}
                {{ form_widget(form.category) }}

                <br>
                {% if edit is defined %}
                    <button type="submit" class="btn btn-secondary">Редактировать</button>
                {% else %}
                    <button type="submit" class="btn btn-secondary">Добавить</button>
                {% endif %}
                {{ form_end(form) }}

            </div>
        </div>
    </div>
{% endblock %}